language: ruby
rvm: 2.2.0
cache: bundler

before_install: nvm install

install:
  - bundle install
  - npm install -g grunt-cli
  - npm install

script: bundle exec rake

after_success:
  - git config --global user.name "$GIT_NAME"
  - git config --global user.email "$GIT_EMAIL"
  - bundle exec rake travis

sudo: false

branches:
  only:
    - master
    - /^greenkeeper/.*$/

env:
  global:
    secure: OZz7QJhBV4FDOJrnq85hJbxhZ3pENNQ3gtQNi/DfSaP8kzpE3gxGtI5fP/gzlBtqwqxWSDCWIec0kVUVqpN9wkehhZcLQjtkfqW5ZFHWihjXSs6rhXT4HSwI5zDqF0dZuF0Es6Pn+5LVoe1MHbRXTXA944WU6xJgQuIwispVd0A=
