language: ruby
rvm: 2.2.0
cache: bundler

before_install: nvm install

install:
  - bundle install
  - npm install -g grunt-cli
  - npm install

script: bundle exec rake

after_success: bundle exec rake travis

env:
  global:
    secure: FrsG8gvP6DdabVugift81EWLIooGSi0axOBoVwMeuAwVqZP+x2QrdrJp/mtka5uJbIvODpOQqqu+Pxa8QYdGjFqg2ay31TLNDQLhuFk8y4V5jJw+vT/DmC4vcL/pmx+R1+bKMVAP1qY4c24QuVhwwekcztHHscfnSi3XsnIn7es=

sudo: false

branches:
  only:
    - master
