# Site settings
title: Travi
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

source: src
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://matt.travi.org" # the base hostname & protocol for your site

openid_delegate: "https://travi.pip.verisignlabs.com"
openid_provider: "https://pip.verisignlabs.com/server"

twitter_username: mtravi
github_username:  travi
keybase_username: travi
lanyrd_username: travi
stackoverflow_username: travi
linkedin_username: matttravi

# Build settings
markdown: kramdown
kramdown:
    input: GFM
sass:
    style: compressed
keep_files: [CNAME, .git, keybase.txt]
